/**
 * Follow-up chips: two or three things the visitor can click to keep going.
 *
 * Researched before built, per CLAUDE.md. The pattern is settled industry
 * practice, not an invention:
 *
 * - Qwairy's GEO study (2026-06-15,
 *   https://www.qwairy.co/blog/ai-follow-up-suggestions-june-2026) measured how
 *   often assistants reopen the conversation: Perplexity ~77% of answers,
 *   ChatGPT ~67%, and roughly double what it was eight months earlier. Google's
 *   AI Overviews sit at ~0% -- a snippet, not a conversation. This bot was on the
 *   AI Overviews end of that spectrum, which is why it read as a dead end.
 * - The chip's SHAPE has to match how the answer ended
 *   (https://github.com/laguagu/claude-code-nextjs-skills, skills/nextjs-chatbot/
 *   suggestions.md, read 2026-09-18). Its warning is the trap here: a single
 *   "suggest three questions" rule emits new questions even right after the bot
 *   asked the visitor something, so the visitor is handed three questions to ask
 *   instead of the one answer they were meant to give. It also notes the
 *   detection is a small function over the answer's tail, not another model call.
 *
 * Where this departs from the industry, deliberately: the chips are derived from
 * the knowledge base rather than generated by a model. Three reasons, in order of
 * weight. A generated chip can propose a question about something Cadre does not
 * publish, and the bot then has to refuse its own suggestion -- worse than no chip
 * at all, and this product exists to not do that. A second model call per turn on
 * a $5/7-day budget is real money for a non-critical feature. And a deterministic
 * function is testable without the network.
 */

import { FAQ } from '../kb/faq.generated'

export interface FollowUp {
  /** What the visitor sees, and what gets sent when they click. */
  label: string
}

/**
 * How the answer ended, which decides what a chip must be.
 *
 * Adapted from the reference above. `answer-the-bot` is the case that matters:
 * offering new questions when the bot just asked one is the specific failure it
 * names.
 */
type Mode = 'answer-the-bot' | 'open'

/**
 * Does the answer put the next move to the visitor?
 *
 * Exported because the walkthrough needs the same judgement, and it had its own
 * weaker copy that only looked for a question mark. That copy reported turn 3 of
 * a real conversation as a dead end when the bot had closed with "if you tell me
 * what you're trying to solve, I can point at the closest fit" -- a conditional
 * refine, which the Qwairy study finds is the single commonest way ChatGPT keeps
 * a conversation open. Two detectors means the weaker one eventually lies.
 */
export function invitesReply(answer: string): boolean {
  return detectMode(answer) === 'answer-the-bot'
}

function detectMode(answer: string): Mode {
  // The cue is in the closing sentences. Looking further back risks firing on a
  // rhetorical question inside the body of the answer.
  const tail = answer.trim().split(/(?<=[.!?])\s+/).slice(-2).join(' ')
  const asksSomething =
    /\?/.test(tail) || /\b(tell me|let me know|which part|would you like|want me to)\b/i.test(tail)
  return asksSomething ? 'answer-the-bot' : 'open'
}

/**
 * One opening question per scenario, phrased the way a visitor would type it.
 *
 * Keyed by the compiled KB's scenario ids, so a chip can only ever point at
 * something the knowledge base actually covers. A scenario with no entry here
 * simply produces no chip.
 */
const SCENARIO_QUESTIONS: Record<string, string> = {
  services: 'What services does Cadre offer?',
  industries: 'Which industries do you work in?',
  booking: 'How do I book a call with a strategist?',
  'maturity-index': 'What is the AI Maturity Index?',
  portal: 'How does the client portal work?',
  'llm-security': 'How does Cadre approach data security?',
  pricing: 'How does pricing work?',
  company: 'Who is Cadre AI?',
}

/**
 * Does this text raise the topic a keyword names?
 *
 * Substring containment, because the compiled KB's keywords are phrases as often
 * as words -- "what does cadre ai do" sits beside "services". Matching word sets
 * silently drops every phrase, which is a quiet way to get chips that repeat what
 * the visitor already asked.
 */
function mentions(text: string, keywords: readonly string[]): boolean {
  const haystack = ` ${text.toLowerCase().replace(/[^a-z0-9]+/g, ' ')} `
  return keywords.some((k) => {
    const needle = k.toLowerCase().replace(/[^a-z0-9]+/g, ' ').trim()
    return needle !== '' && haystack.includes(` ${needle} `)
  })
}

/**
 * Chips for the turn that just happened.
 *
 * `asked` and `answered` are the visitor's message and the bot's reply. Returns
 * at most three, never repeating a topic the visitor has already raised.
 */
export function followUpsFor(asked: string, answered: string, history: string[] = []): FollowUp[] {
  if (answered.trim() === '') return []

  if (detectMode(answered) === 'answer-the-bot') {
    // The bot asked something. Offering unrelated questions here would talk over
    // it, so the visitor gets nothing and answers in their own words.
    return []
  }

  const seen = [asked, ...history].join(' ')

  const scored = FAQ.map((entry) => {
    const question = SCENARIO_QUESTIONS[entry.scenario]
    if (question === undefined) return null

    // Already covered, either by this question or one earlier in the conversation.
    if (mentions(seen, entry.keywords)) return null

    // Prefer a scenario the answer already brushed against, so the chips read as a
    // continuation rather than a menu of everything the bot knows.
    const overlap = entry.keywords.filter((k) => mentions(answered, [k])).length
    return { question, overlap }
  }).filter((s): s is { question: string; overlap: number } => s !== null)

  // Adjacency first, then the KB's own order, which puts the common questions up
  // front. A stable sort keeps that order inside each overlap band.
  scored.sort((a, b) => b.overlap - a.overlap)

  return scored.slice(0, 3).map(({ question }) => ({ label: question }))
}
