// GENERATED BY `pnpm kb:compile` FROM kb/*.md -- DO NOT EDIT.
// Edit the markdown in kb/ and re-run the compiler.
import type { FaqEntry } from './compile'

export const FAQ: readonly FaqEntry[] = [
  {
    "scenario": "services",
    "keywords": [
      "what does cadre ai do",
      "what does cadre do",
      "what do you do",
      "what you do",
      "services",
      "service lines",
      "offer",
      "offerings",
      "capabilities",
      "what can you help",
      "strategy",
      "engineering",
      "agents",
      "leadership",
      "facilitation",
      "consultancy"
    ],
    "answer": "Cadre AI is an AI strategy and implementation consultancy with four service lines: AI Strategy, AI Leadership & Facilitation, AI Engineering, and AI Agents. In practice that runs from finding the right problems and building a prioritised roadmap, through workflow automation and systems integration, to voice and chat agents that run end-to-end processes with guardrails and human oversight. If you tell me what you're trying to solve I can point you at the closest fit, or you can reach a strategist at https://www.cadreai.com/contact.",
    "source": "02-services.md"
  },
  {
    "scenario": "pricing",
    "keywords": [
      "price",
      "pricing",
      "cost",
      "costs",
      "how much",
      "quote",
      "budget",
      "rate",
      "rates",
      "fee",
      "fees",
      "ballpark",
      "estimate",
      "expensive",
      "contract",
      "retainer",
      "discount"
    ],
    "answer": "Cadre doesn't publish pricing, and I won't guess at a range — engagement scope varies too much for a number from me to be useful or accurate. Pricing comes from a conversation with their team: https://www.cadreai.com/contact. If you'd rather not chase it, give me your name, work email and company and I'll pass your details along.",
    "source": "02-services.md"
  },
  {
    "scenario": "industries",
    "keywords": [
      "industry",
      "industries",
      "sector",
      "vertical",
      "do you work with",
      "work with my",
      "private equity",
      "construction",
      "manufacturing",
      "retail",
      "financial services",
      "real estate",
      "hospitality",
      "professional services"
    ],
    "answer": "Cadre works with B2B companies and publishes work across professional services, private equity, financial services, real estate, mortgage and lending, construction, retail and e-commerce, manufacturing and logistics, and hospitality. The published example I can point to in detail is private equity — deal sourcing and due diligence work like CIM analysis, financial modeling and contract review. If your industry isn't on that list I won't guess whether it's a fit; a strategist can tell you directly at https://www.cadreai.com/contact, or I can pass your details to the team.",
    "source": "03-industries.md"
  },
  {
    "scenario": "booking",
    "keywords": [
      "book",
      "booking",
      "call",
      "meeting",
      "demo",
      "schedule",
      "scheduling",
      "appointment",
      "talk to",
      "speak to",
      "get started",
      "contact",
      "reach out",
      "consultation"
    ],
    "answer": "You can reach a Cadre strategist through the contact page at https://www.cadreai.com/contact. If you'd rather I pass along your details, tell me your name, work email, company and what you're trying to solve, and I'll send it to the team.",
    "source": "04-getting-started.md"
  },
  {
    "scenario": "maturity-index",
    "keywords": [
      "maturity index",
      "ai maturity",
      "maturity",
      "index",
      "pillar",
      "pillars",
      "score",
      "scored",
      "scoring",
      "assessment",
      "framework",
      "eight pillar",
      "8 pillar"
    ],
    "answer": "Cadre runs the Index as part of working with their team rather than as a self-serve quiz, so the way to get scored is to talk to a strategist — https://www.cadreai.com/contact. I can also pass your details along if that's easier.",
    "source": "05-ai-maturity-index.md"
  },
  {
    "scenario": "portal",
    "keywords": [
      "portal",
      "login",
      "log in",
      "sign in",
      "dashboard",
      "access",
      "my account",
      "account access",
      "client portal",
      "track my",
      "my agents",
      "my results"
    ],
    "answer": "Cadre does give clients a central portal for tracking tools, agents, training and results — but access is set up per client and I don't have a login link I can verify, so I'd be guessing if I gave you one. The fastest route is your Cadre contact, or the contact page at https://www.cadreai.com/contact. If you give me your name, work email and company I'll pass the access request to the team.",
    "source": "06-client-portal.md"
  },
  {
    "scenario": "llm-security",
    "keywords": [
      "llm",
      "model",
      "models",
      "which model",
      "security",
      "secure",
      "data",
      "privacy",
      "compliance",
      "compliant",
      "soc 2",
      "soc2",
      "gdpr",
      "hipaa",
      "iso",
      "retention",
      "residency",
      "dpa",
      "encryption",
      "safe",
      "training data",
      "sub-processor"
    ],
    "answer": "Two things I can tell you. Cadre works with OpenAI, Anthropic, Google, Microsoft, AWS, Salesforce and Snowflake, and uses OpenRouter for model access — so model choice is made per workload rather than locked to one vendor. And guardrails with human oversight are part of what they build, not an add-on. What I can't do is state Cadre's security, privacy, retention or compliance position: they don't publish one, and that's a contractual answer their team gives against your actual requirements, not something a chatbot should improvise. https://www.cadreai.com/contact, or I can pass your details on.",
    "source": "07-llm-and-security.md"
  },
  {
    "scenario": "fallback",
    "keywords": [
      "human",
      "person",
      "someone",
      "agent",
      "representative",
      "rep",
      "help",
      "support",
      "talk to a human",
      "speak to someone",
      "escalate"
    ],
    "answer": "I can't connect you to someone live, but I can take your details and pass them to the Cadre team. I can't promise a response time — that's up to them. You can also reach them directly at https://www.cadreai.com/contact.",
    "source": "08-contact-and-escalation.md"
  }
]
